// components/options/OptionsApp.svelte
<script lang="ts">
  // SPDX-License-Identifier: AGPL-3.0-or-later
  //
  // OptionsApp (plan Phase 5 Step 8). The settings + privacy surface. It mounts the
  // SAME theme applier as the replay App (so changing the theme here restyles both
  // pages live), parses an optional `?doc=` for per-document cache clearing, and
  // wires every `lib/platform/settings.ts` item through a one-shot read on mount +
  // `setValue` (write). Never displays raw document data.
  //
  // Visual register: iOS-Settings — a warm canvas, a reassuring privacy banner, then
  // quiet group labels over grouped-row cards. Boolean settings are friendly switches
  // (a native checkbox kept for a11y + tests, styled as a switch via `peer-checked:`);
  // the theme is a segmented control; storage caps are unit-suffixed number fields.
  //
  // The three row shapes (`SwitchRow`, `BudgetRow`, `MaintenanceNote`) are sibling
  // components — Svelte allows one component per file.

  import { onMount } from "svelte";
  import BrandMark from "@/components/common/BrandMark.svelte";
  import PrivacySummary from "@/components/common/PrivacySummary.svelte";
  import ThemeControl from "@/components/common/ThemeControl.svelte";
  import { useThemeSync } from "@/components/common/theme-sync.svelte";
  import BudgetRow from "@/components/options/BudgetRow.svelte";
  import CacheControls from "@/components/options/CacheControls.svelte";
  import DiagnosticsPreferences from "@/components/options/DiagnosticsPreferences.svelte";
  import MaintenanceNote from "@/components/options/MaintenanceNote.svelte";
  import SwitchRow from "@/components/options/SwitchRow.svelte";
  import { asDocId } from "@/lib/core/domain/ids";
  import type { DocId } from "@/lib/core/domain/model";
  import { strings } from "@/lib/core/i18n/strings";
  import { createIdbStore } from "@/lib/platform/db";
  import { sendMessage } from "@/lib/platform/messaging";
  import {
    createPendingDestructiveStorageClear,
    createPendingStorageMaintenanceRequest,
    getPendingDestructiveStorageClears,
    getPendingStorageMaintenance,
    keepRawData,
    realIdentities,
    removePendingDestructiveStorageClear,
    removePendingStorageMaintenance,
    resolvedIdentities,
    type StorageBudget,
    storageBudget,
    upsertPendingDestructiveStorageClear,
    upsertPendingStorageMaintenance,
  } from "@/lib/platform/settings";

  const MIB = 1024 * 1024;

  function parseDocId(search: string): DocId | null {
    const raw = new URLSearchParams(search).get("doc");
    if (raw === null) {
      return null;
    }
    try {
      return asDocId(raw);
    } catch {
      return null;
    }
  }

  useThemeSync();

  const store = createIdbStore();
  const docId = parseDocId(window.location.search);

  // Read-once + optimistic local overwrite for each persisted item (the old
  // `createResource` + `mutate` pairs): the row repaints immediately while the
  // async `setValue` lands.
  let keepRaw = $state<boolean | undefined>(undefined);
  let showIdentities = $state<boolean | undefined>(undefined);
  let budget = $state<StorageBudget | undefined>(undefined);
  let maintenanceStatus = $state<"pending" | "failed" | null>(null);

  onMount(() => {
    void (async () => {
      keepRaw = await keepRawData.getValue();
    })();
    void (async () => {
      showIdentities = await realIdentities.getValue();
    })();
    void (async () => {
      budget = await storageBudget.getValue();
    })();
    void refreshPendingStatus();
  });

  function onKeepRaw(next: boolean): void {
    keepRaw = next;
    void keepRawData.setValue(next);
    const currentBudget = budget;
    void (async () => {
      const resolvedBudget = currentBudget ?? (await storageBudget.getValue());
      await sendDurableMaintenance({
        docId,
        keepRawData: next,
        budget: resolvedBudget,
      });
    })().catch(() => {
      maintenanceStatus = "failed";
    });
  }

  function onIdentities(next: boolean): void {
    showIdentities = next;
    void realIdentities.setValue(next);
    // Opting out falls back to opaque labels: drop the resolved-name cache so the
    // privacy promise is instantaneous, not deferred to session end (lib/platform/settings.ts).
    if (!next) {
      void resolvedIdentities.removeValue();
    }
  }

  function onBudget(field: "perDocumentBytes" | "globalCapBytes", mib: number): void {
    const current = budget;
    if (current === undefined || !Number.isFinite(mib) || mib <= 0) {
      return;
    }
    const next = { ...current, [field]: Math.round(mib * MIB) };
    budget = next;
    void storageBudget.setValue(next);
    void sendDurableMaintenance({
      docId,
      keepRawData: keepRaw ?? true,
      budget: next,
    }).catch(() => {
      maintenanceStatus = "failed";
    });
  }

  async function sendDurableMaintenance(input: {
    readonly docId: DocId | null;
    readonly keepRawData: boolean;
    readonly budget: StorageBudget;
  }): Promise<void> {
    const request = createPendingStorageMaintenanceRequest(input);
    await upsertPendingStorageMaintenance(request);
    maintenanceStatus = "pending";
    try {
      const ack = await sendMessage("requestStorageMaintenance", request);
      if (ack.status === "completed") {
        await removePendingStorageMaintenance(request.id, request.queuedAt);
        await refreshPendingStatus();
      } else {
        maintenanceStatus = ack.status === "failed" ? "failed" : "pending";
      }
    } catch {
      maintenanceStatus = "failed";
    }
  }

  async function refreshPendingStatus(): Promise<void> {
    const [pendingMaintenance, pendingClears] = await Promise.all([
      getPendingStorageMaintenance(),
      getPendingDestructiveStorageClears(),
    ]);
    maintenanceStatus =
      pendingMaintenance.length > 0 || pendingClears.length > 0 ? "pending" : null;
  }

  async function clearDocumentCache(targetDocId: DocId): Promise<void> {
    const request = createPendingDestructiveStorageClear({
      kind: "document",
      docId: targetDocId,
    });
    await upsertPendingDestructiveStorageClear(request);
    maintenanceStatus = "pending";
    try {
      const ack = await sendMessage("clearDocumentCache", request);
      if (ack.status === "completed") {
        await removePendingDestructiveStorageClear(request);
        await refreshPendingStatus();
      } else {
        maintenanceStatus = ack.status === "failed" ? "failed" : "pending";
      }
    } catch {
      maintenanceStatus = "failed";
    }
  }

  async function clearAllCaches(): Promise<void> {
    const request = createPendingDestructiveStorageClear({ kind: "all" });
    await upsertPendingDestructiveStorageClear(request);
    maintenanceStatus = "pending";
    try {
      const ack = await sendMessage("clearAllCaches", request);
      if (ack.status === "completed") {
        await removePendingDestructiveStorageClear(request);
        await refreshPendingStatus();
      } else {
        maintenanceStatus = ack.status === "failed" ? "failed" : "pending";
      }
    } catch {
      maintenanceStatus = "failed";
    }
  }
</script>

<div class="dr-page">
  <main class="mx-auto flex max-w-2xl flex-col gap-8 p-6 sm:p-8">
    <header class="flex items-center gap-3">
      <BrandMark size={36} />
      <h1 class="dr-title">{strings.options.title}</h1>
    </header>

    <PrivacySummary />

    <section class="dr-group" aria-labelledby="dr-appearance-heading">
      <h2 id="dr-appearance-heading" class="dr-group-label">
        {strings.options.settingsHeading}
      </h2>
      <div class="dr-rows">
        <ThemeControl />
      </div>
    </section>

    <section class="dr-group" aria-labelledby="dr-data-heading">
      <h2 id="dr-data-heading" class="dr-group-label">
        {strings.options.privacyHeading}
      </h2>
      <div class="dr-rows">
        <SwitchRow
          label={strings.options.realIdentitiesLabel}
          help={strings.options.realIdentitiesHint}
          checked={showIdentities ?? true}
          onChange={onIdentities}
        />
        <SwitchRow
          label={strings.options.keepRawLabel}
          help={strings.options.keepRawHint}
          checked={keepRaw ?? true}
          onChange={onKeepRaw}
        />
      </div>
    </section>

    <section class="dr-group" aria-labelledby="dr-cache-heading">
      <h2 id="dr-cache-heading" class="dr-group-label">
        {strings.options.cacheHeading}
      </h2>
      <div class="dr-rows">
        <BudgetRow
          id="dr-per-document-cap"
          label={strings.options.perDocumentCapLabel}
          value={Math.round((budget?.perDocumentBytes ?? 0) / MIB)}
          onInput={(mib) => onBudget("perDocumentBytes", mib)}
        />
        <BudgetRow
          id="dr-global-cap"
          label={strings.options.globalCapLabel}
          value={Math.round((budget?.globalCapBytes ?? 0) / MIB)}
          onInput={(mib) => onBudget("globalCapBytes", mib)}
        />
      </div>

      <CacheControls
        {store}
        {docId}
        onClearDocument={clearDocumentCache}
        onClearAll={clearAllCaches}
      />
    </section>

    <DiagnosticsPreferences />

    {#if maintenanceStatus}
      {@const status = maintenanceStatus}
      <MaintenanceNote failed={status === "failed"} />
    {/if}
  </main>
</div>

// components/options/OptionsApp.tsx
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// OptionsApp (plan Phase 5 Step 8). The settings + privacy surface. It mounts the
// SAME theme applier as the replay App (so changing the theme here restyles both
// pages live), parses an optional `?doc=` for per-document cache clearing, and
// wires every `lib/platform/settings.ts` item through `createResource` (read) + `setValue`
// (write). Never displays raw document data.
//
// Visual register: iOS-Settings — a warm canvas, a reassuring privacy banner, then
// quiet group labels over grouped-row cards. Boolean settings are friendly switches
// (a native checkbox kept for a11y + tests, styled as a switch via `peer-checked:`);
// the theme is a segmented control; storage caps are unit-suffixed number fields.

import type { Component, JSX } from "solid-js";
import { createResource, createSignal, onMount, Show } from "solid-js";
import BrandMark from "@/components/common/BrandMark";
import { IconAlert, IconInfo } from "@/components/common/icons";
import PrivacySummary from "@/components/common/PrivacySummary";
import ThemeControl from "@/components/common/ThemeControl";
import { useThemeSync } from "@/components/common/theme-sync";
import CacheControls from "@/components/options/CacheControls";
import DiagnosticsPreferences from "@/components/options/DiagnosticsPreferences";
import { asDocId } from "@/lib/core/domain/ids";
import type { DocId } from "@/lib/core/domain/model";
import { strings } from "@/lib/core/i18n/strings";
import { createIdbStore } from "@/lib/platform/db";
import { sendMessage } from "@/lib/platform/messaging";
import {
  createPendingDestructiveStorageClear,
  createPendingStorageMaintenanceRequest,
  getPendingDestructiveStorageClears,
  getPendingStorageMaintenance,
  keepRawData,
  realIdentities,
  removePendingDestructiveStorageClear,
  removePendingStorageMaintenance,
  resolvedIdentities,
  type StorageBudget,
  storageBudget,
  upsertPendingDestructiveStorageClear,
  upsertPendingStorageMaintenance,
} from "@/lib/platform/settings";

const MIB = 1024 * 1024;

function parseDocId(search: string): DocId | null {
  const raw = new URLSearchParams(search).get("doc");
  if (raw === null) {
    return null;
  }
  try {
    return asDocId(raw);
  } catch {
    return null;
  }
}

/**
 * A grouped settings row carrying a boolean as a friendly switch. A real
 * `<input type="checkbox">` is kept (visually-hidden via `sr-only peer`) so the
 * label association, `checked` state, and the existing tests/e2e selectors stay
 * intact; the switch track + knob are painted with `peer-checked:` utilities. The
 * one-line help sits OUTSIDE the `<label>` so the input's accessible name remains
 * exactly the title text.
 */
const SwitchRow: Component<{
  readonly label: string;
  readonly help: string;
  readonly checked: boolean;
  readonly onChange: (next: boolean) => void;
}> = (props) => {
  return (
    <div class="dr-row-stack">
      <label class="flex cursor-pointer items-center justify-between gap-4">
        <span class="dr-row-label">{props.label}</span>
        <span class="relative inline-flex shrink-0 items-center">
          <input
            type="checkbox"
            class="peer sr-only"
            checked={props.checked}
            onChange={(event) => props.onChange(event.currentTarget.checked)}
          />
          <span
            class="block h-[1.6rem] w-[2.75rem] rounded-full bg-hairline-strong transition-colors duration-200 ease-[var(--dr-ease-out)] peer-checked:bg-brand peer-focus-visible:ring-2 peer-focus-visible:ring-brand-ring peer-focus-visible:ring-offset-2 peer-focus-visible:ring-offset-surface"
            aria-hidden="true"
          />
          <span
            class="pointer-events-none absolute left-[0.2rem] size-[1.2rem] rounded-full bg-white shadow-[var(--dr-shadow-sm)] transition-transform duration-200 ease-[var(--dr-ease-out)] peer-checked:translate-x-[1.15rem]"
            aria-hidden="true"
          />
        </span>
      </label>
      <p class="dr-row-help">{props.help}</p>
    </div>
  );
};

/**
 * A grouped settings row carrying a byte budget as a unit-suffixed number field.
 * Keeps `type="number"` + `min` and the original label association (a `<label>`
 * wrapping the title + input) so `findByLabelText` and `.value` stay stable.
 */
const BudgetRow: Component<{
  readonly id: string;
  readonly label: string;
  readonly value: number;
  readonly onInput: (mib: number) => void;
}> = (props) => {
  // Explicit `for`/`id` association (not a wrapping label) so the input's
  // accessible name is EXACTLY the title — the friendly "MB" suffix must not leak
  // into it (tests query `findByLabelText("Global cap (MB)")` etc.).
  return (
    <div class="dr-row">
      <label for={props.id} class="dr-row-label">
        {props.label}
      </label>
      <span class="dr-field">
        <input
          id={props.id}
          type="number"
          min={1}
          class="dr-field-input"
          value={props.value}
          onChange={(event) => props.onInput(Number(event.currentTarget.value))}
        />
        <span class="dr-field-suffix" aria-hidden="true">
          MB
        </span>
      </span>
    </div>
  );
};

const OptionsApp: Component = () => {
  useThemeSync();

  const store = createIdbStore();
  const docId = parseDocId(window.location.search);

  const [keepRaw, { mutate: mutateKeepRaw }] = createResource(() => keepRawData.getValue());
  const [showIdentities, { mutate: mutateIdentities }] = createResource(() =>
    realIdentities.getValue(),
  );
  const [budget, { mutate: mutateBudget }] = createResource(() => storageBudget.getValue());
  const [maintenanceStatus, setMaintenanceStatus] = createSignal<"pending" | "failed" | null>(null);

  onMount(() => {
    void refreshPendingStatus();
  });

  function onKeepRaw(next: boolean): void {
    mutateKeepRaw(next);
    void keepRawData.setValue(next);
    const currentBudget = budget();
    void (async () => {
      const resolvedBudget = currentBudget ?? (await storageBudget.getValue());
      await sendDurableMaintenance({
        docId,
        keepRawData: next,
        budget: resolvedBudget,
      });
    })().catch(() => setMaintenanceStatus("failed"));
  }

  function onIdentities(next: boolean): void {
    mutateIdentities(next);
    void realIdentities.setValue(next);
    // Opting out falls back to opaque labels: drop the resolved-name cache so the
    // privacy promise is instantaneous, not deferred to session end (lib/platform/settings.ts).
    if (!next) {
      void resolvedIdentities.removeValue();
    }
  }

  function onBudget(field: "perDocumentBytes" | "globalCapBytes", mib: number): void {
    const current = budget();
    if (current === undefined || !Number.isFinite(mib) || mib <= 0) {
      return;
    }
    const next = { ...current, [field]: Math.round(mib * MIB) };
    mutateBudget(next);
    void storageBudget.setValue(next);
    void sendDurableMaintenance({
      docId,
      keepRawData: keepRaw() ?? true,
      budget: next,
    }).catch(() => setMaintenanceStatus("failed"));
  }

  async function sendDurableMaintenance(input: {
    readonly docId: DocId | null;
    readonly keepRawData: boolean;
    readonly budget: StorageBudget;
  }): Promise<void> {
    const request = createPendingStorageMaintenanceRequest(input);
    await upsertPendingStorageMaintenance(request);
    setMaintenanceStatus("pending");
    try {
      const ack = await sendMessage("requestStorageMaintenance", request);
      if (ack.status === "completed") {
        await removePendingStorageMaintenance(request.id, request.queuedAt);
        await refreshPendingStatus();
      } else {
        setMaintenanceStatus(ack.status === "failed" ? "failed" : "pending");
      }
    } catch {
      setMaintenanceStatus("failed");
    }
  }

  async function refreshPendingStatus(): Promise<void> {
    const [pendingMaintenance, pendingClears] = await Promise.all([
      getPendingStorageMaintenance(),
      getPendingDestructiveStorageClears(),
    ]);
    setMaintenanceStatus(
      pendingMaintenance.length > 0 || pendingClears.length > 0 ? "pending" : null,
    );
  }

  async function clearDocumentCache(targetDocId: DocId): Promise<void> {
    const request = createPendingDestructiveStorageClear({
      kind: "document",
      docId: targetDocId,
    });
    await upsertPendingDestructiveStorageClear(request);
    setMaintenanceStatus("pending");
    try {
      const ack = await sendMessage("clearDocumentCache", request);
      if (ack.status === "completed") {
        await removePendingDestructiveStorageClear(request);
        await refreshPendingStatus();
      } else {
        setMaintenanceStatus(ack.status === "failed" ? "failed" : "pending");
      }
    } catch {
      setMaintenanceStatus("failed");
    }
  }

  async function clearAllCaches(): Promise<void> {
    const request = createPendingDestructiveStorageClear({ kind: "all" });
    await upsertPendingDestructiveStorageClear(request);
    setMaintenanceStatus("pending");
    try {
      const ack = await sendMessage("clearAllCaches", request);
      if (ack.status === "completed") {
        await removePendingDestructiveStorageClear(request);
        await refreshPendingStatus();
      } else {
        setMaintenanceStatus(ack.status === "failed" ? "failed" : "pending");
      }
    } catch {
      setMaintenanceStatus("failed");
    }
  }

  return (
    <div class="dr-page">
      <main class="mx-auto flex max-w-2xl flex-col gap-8 p-6 sm:p-8">
        <header class="flex items-center gap-3">
          <BrandMark size={36} />
          <h1 class="dr-title">{strings.options.title}</h1>
        </header>

        <PrivacySummary />

        <section class="dr-group" aria-labelledby="dr-appearance-heading">
          <h2 id="dr-appearance-heading" class="dr-group-label">
            {strings.options.settingsHeading}
          </h2>
          <div class="dr-rows">
            <ThemeControl />
          </div>
        </section>

        <section class="dr-group" aria-labelledby="dr-data-heading">
          <h2 id="dr-data-heading" class="dr-group-label">
            {strings.options.privacyHeading}
          </h2>
          <div class="dr-rows">
            <SwitchRow
              label={strings.options.realIdentitiesLabel}
              help={strings.options.realIdentitiesHint}
              checked={showIdentities() ?? true}
              onChange={onIdentities}
            />
            <SwitchRow
              label={strings.options.keepRawLabel}
              help={strings.options.keepRawHint}
              checked={keepRaw() ?? true}
              onChange={onKeepRaw}
            />
          </div>
        </section>

        <section class="dr-group" aria-labelledby="dr-cache-heading">
          <h2 id="dr-cache-heading" class="dr-group-label">
            {strings.options.cacheHeading}
          </h2>
          <div class="dr-rows">
            <BudgetRow
              id="dr-per-document-cap"
              label={strings.options.perDocumentCapLabel}
              value={Math.round((budget()?.perDocumentBytes ?? 0) / MIB)}
              onInput={(mib) => onBudget("perDocumentBytes", mib)}
            />
            <BudgetRow
              id="dr-global-cap"
              label={strings.options.globalCapLabel}
              value={Math.round((budget()?.globalCapBytes ?? 0) / MIB)}
              onInput={(mib) => onBudget("globalCapBytes", mib)}
            />
          </div>

          <CacheControls
            store={store}
            docId={docId}
            onClearDocument={clearDocumentCache}
            onClearAll={clearAllCaches}
          />
        </section>

        <DiagnosticsPreferences />

        <Show when={maintenanceStatus()}>
          {(status) => <MaintenanceNote failed={status() === "failed"} />}
        </Show>
      </main>
    </div>
  );
};

const MaintenanceNote: Component<{ readonly failed: boolean }> = (props): JSX.Element => {
  return (
    <p class={props.failed ? "note-warning" : "note-info"} role="status">
      <Show when={props.failed} fallback={<IconInfo size={18} class="note-icon" />}>
        <IconAlert size={18} class="note-icon" />
      </Show>
      <span>
        {props.failed ? strings.options.maintenanceFailed : strings.options.maintenancePending}
      </span>
    </p>
  );
};

export default OptionsApp;
